export const ROUTES = {
  ROOT:                   '/',
  LOGIN_ADMIN:            '/login/admin',
  LOGIN_SUPERVISOR:       '/login/supervisor',
  LOGIN_HELPER:           '/login/helper',
  LOGIN_HELPEE:           '/login/helpee',

  ADMIN_HOME:             '/admin/home',
  ADMIN_MANAGE_USERS:     '/admin/manage-users',
  ADMIN_USER_VIEW:        '/admin/users/:id',
  ADMIN_USER_EDIT:        '/admin/users/:id/edit',
  ADMIN_USER_NEW:         '/admin/users/new',
  ADMIN_MANAGE_JOBS:      '/admin/manage-jobs',
  ADMIN_JOB_NEW:          '/admin/jobs/new',
  ADMIN_JOB_NEW_FREQUENT: '/admin/jobs/new/frequent',
  ADMIN_JOB_VIEW:         '/admin/jobs/:id',
  ADMIN_JOB_SPECS:        '/admin/job-specs',
  ADMIN_JOB_SPEC_NEW:     '/admin/job-specs/new',
  ADMIN_JOB_SPEC_EDIT:    '/admin/job-specs/:id/edit',
  ADMIN_SETUP:            '/admin/setup',
  ADMIN_DEPARTMENTS:      '/admin/departments',
  ADMIN_DEPT_NEW:         '/admin/departments/new',
  ADMIN_DEPT_EDIT:        '/admin/departments/:id/edit',
  ADMIN_SEARCH_USERS:     '/admin/search-users',
  ADMIN_SEARCH_USERS_DEPT:'/admin/search-users/dept',
  ADMIN_NOTIFICATIONS:    '/admin/notifications',

  SUPERVISOR_HOME:        '/supervisor/home',
  HELPER_HOME:            '/helper/home',
  HELPEE_HOME:            '/helpee/home',

  NOTIFICATIONS:          '/notifications',
  PROFILE:                '/profile',
}
